### ISSUE TITLE
automysqlbackup cron job tries to set ownership on /var/backup/db* and fails

### ISSUE THREAD

**Issue by Drachenkaetzchen** [nextrevision/puppet-automysqlbackup#1]
Hi,

thanks for that puppet module. There's a problem with /etc/cron.daily/automysqlbackup:

> chown root.root /var/backup/db\* -R
> find <%= backup_dir %>/\* -type f -exec chmod 400 {} \;
> find <%= backup_dir %>/\* -type d -exec chmod 700 {} \;

I'm not sure if that's really necessary; I believe that should be optional and not hardcoded.

**Comment by nextrevision** [comment]
Thanks for using the module. Yes that is a mistake on my part. I have updated the script to include an option to disable cron setting permissions and also removed the static directory in place of the 'backup_dir' variable.

Thanks for the notification!

**Comment by nextrevision** [comment]
Change has been built and tested. Available in the Github repository and on Puppet Forge (v0.1.3)
