### ISSUE TITLE
backup_dir mode is 0755 (world readable)

### ISSUE THREAD

**Issue by mamchenkov** [nextrevision/puppet-automysqlbackup#10]
Firstly, thanks for the module!   :smile: 

Secondly, the permission of the backup_dir is set to 0755 (in `manifests/init.pp:102`).  This makes backups world-readable, which isn't always ideal.  Either a configuration option is needed, or a more restrictive mode, like 0750 - for user and group only readable.

**Comment by gibbs** [comment]
The backups themselves aren't. They default to root:root and 0700/0400 which can be configured in `::automysqlbackup::backup` at [L56](https://github.com/nextrevision/puppet-automysqlbackup/blob/master/manifests/backup.pp#L56). 

```
$backup_dir_owner = 'root',
$backup_dir_group = 'root',
$backup_dir_perms = '0700',
$backup_file_perms = '0400',
```

**Comment by mamchenkov** [comment]
Indeed.  My bad, sorry.
