### ISSUE TITLE
module on forge is broken

### ISSUE THREAD

**Issue by rjw1** [nextrevision/puppet-automysqlbackup#5]
the 0.2.1 tarball on the forge doesnt actually contain the manifests.

**Comment by nextrevision** [comment]
Wow, you're absolutely right. Not quite sure how that happened. Deployed via Geppetto for the first time, so there might have been something I missed with that. I'll fix that right away and update it with the recent changes. Thanks for the heads up.

**Comment by rjw1** [comment]
indeed. hold off a sec. ive got another patch to fix some deprecation warnings in the templates.

**Comment by nextrevision** [comment]
OK, issue another pull request and I'll go through it this afternoon at the latest.

**Comment by nextrevision** [comment]
Thanks for the contributions! Verified the forge module works as expected.
